var app = angular.module('App', []);

app.filter('firstName', function() {
  return function(input, firstName) {
    var filtered = [];
    var firstName = new RegExp(firstName, 'i');
    for(var i = 0; i < input.length; i++){
      if(firstName.test(input[i])){
        filtered.push(input[i]);
      }
    }
    return filtered;
  };
});
app.filter('lastName', function() {
  return function(input, lastName) {
    var filtered = [];
    var lastName = new RegExp(lastName, 'i');
    for(var i = 0; i < input.length; i++){
      if(lastName.test(input[i])){
        filtered.push(input[i]);
      }
    }
    return filtered;
  };
});
app.filter('age', function() {
  return function(input, age) {
    var filtered = [];
    var age = new RegExp(age, 'i');
    for(var i = 0; i < input.length; i++){
      if(age.test(input[i])){
        filtered.push(input[i]);
      }
    }
    return filtered;
  };
});

app.controller('myController', ['$scope', function($scope) {
    $scope.users = [
      {
        "first_name": "Stephen",
        "last_name": "Brown",
        "age": 26
      }, {
        "first_name": "Johnny",
        "last_name": "Foster",
        "age": 11
      }, {
        "first_name": "Robert",
        "last_name": "Ong",
        "age": 29
      }, {
        "first_name": "Jonathan",
        "last_name": "Chavez",
        "age": 92
      }, {
        "first_name": "Heather",
        "last_name": "Williams",
        "age": 7
      }, {
        "first_name": "Irene",
        "last_name": "Johnston",
        "age": 27
      }, {
        "first_name": "Emily",
        "last_name": "Rivera",
        "age": 20
      }, {
        "first_name": "Charles",
        "last_name": "Nguyen",
        "age": 63
      }, {
        "first_name": "Thomas",
        "last_name": "Gordon",
        "age": 45
      }, {
        "first_name": "Raymond",
        "last_name": "Brooks",
        "age": 27
      }, {
        "first_name": "Steve",
        "last_name": "Schmidt",
        "age": 90
      }, {
        "first_name": "Norma",
        "last_name": "Willis",
        "age": 17
      }, {
        "first_name": "Jane",
        "last_name": "Simpson",
        "age": 6
      }, {
        "first_name": "Louis",
        "last_name": "Myers",
        "age": 19
      }, {
        "first_name": "Tammy",
        "last_name": "Turner",
        "age": 43
      }, {
        "first_name": "Jacqueline",
        "last_name": "Arnold",
        "age": 18
      }, {
        "first_name": "Roger",
        "last_name": "Ryan",
        "age": 71
      }, {
        "first_name": "Stephanie",
        "last_name": "Carroll",
        "age": 65
      }, {
        "first_name": "Mark",
        "last_name": "Phillips",
        "age": 27
      }, {
        "first_name": "David",
        "last_name": "Watkins",
        "age": 74
      }, {
        "first_name": "Raymond",
        "last_name": "Miller",
        "age": 37
      }, {
        "first_name": "Kimberly",
        "last_name": "Stanley",
        "age": 90
      }, {
        "first_name": "Samuel",
        "last_name": "Tucker",
        "age": 65
      }, {
        "first_name": "Lawrence",
        "last_name": "Graham",
        "age": 45
      }, {
        "first_name": "Christopher",
        "last_name": "Ross",
        "age": 79
      }, {
        "first_name": "Helen",
        "last_name": "Taylor",
        "age": 29
      }, {
        "first_name": "Samuel",
        "last_name": "Henry",
        "age": 97
      }, {
        "first_name": "Sharon",
        "last_name": "Fuller",
        "age": 35
      }, {
        "first_name": "Gary",
        "last_name": "Evans",
        "age": 13
      }, {
        "first_name": "Andrea",
        "last_name": "Russell",
        "age": 1
      }, {
        "first_name": "Rachel",
        "last_name": "Wilson",
        "age": 23
      }, {
        "first_name": "George",
        "last_name": "Collins",
        "age": 72
      }, {
        "first_name": "Earl",
        "last_name": "Boyd",
        "age": 37
      }, {
        "first_name": "Maria",
        "last_name": "Franklin",
        "age": 59
      }, {
        "first_name": "Aaron",
        "last_name": "Harper",
        "age": 52
      }, {
        "first_name": "Ruth",
        "last_name": "Dean",
        "age": 98
      }, {
        "first_name": "Deborah",
        "last_name": "Rose",
        "age": 70
      }, {
        "first_name": "Gerald",
        "last_name": "Simmons",
        "age": 56
      }, {
        "first_name": "Ann",
        "last_name": "Patterson",
        "age": 23
      }, {
        "first_name": "Phyllis",
        "last_name": "Woods",
        "age": 66
      }, {
        "first_name": "Brian",
        "last_name": "Morgan",
        "age": 76
      }, {
        "first_name": "Bobby",
        "last_name": "Hill",
        "age": 37
      }, {
        "first_name": "Jean",
        "last_name": "George",
        "age": 50
      }, {
        "first_name": "Paula",
        "last_name": "Gomez",
        "age": 96
      }, {
        "first_name": "Steve",
        "last_name": "Gilbert",
        "age": 39
      }, {
        "first_name": "Kevin",
        "last_name": "West",
        "age": 5
      }, {
        "first_name": "Lawrence",
        "last_name": "Medina",
        "age": 33
      }, {
        "first_name": "Mildred",
        "last_name": "Thompson",
        "age": 27
      }, {
        "first_name": "Jerry",
        "last_name": "Barnes",
        "age": 67
      }, {
        "first_name": "Deborah",
        "last_name": "Perry",
        "age": 82
      }, {
        "first_name": "Nancy",
        "last_name": "Lawrence",
        "age": 33
      }, {
        "first_name": "Diane",
        "last_name": "King",
        "age": 36
      }, {
        "first_name": "Paul",
        "last_name": "Webb",
        "age": 24
      }, {
        "first_name": "Pamela",
        "last_name": "Dixon",
        "age": 87
      }, {
        "first_name": "Larry",
        "last_name": "King",
        "age": 13
      }, {
        "first_name": "Rose",
        "last_name": "Berry",
        "age": 11
      }, {
        "first_name": "Gregory",
        "last_name": "Howard",
        "age": 82
      }, {
        "first_name": "Frank",
        "last_name": "Ward",
        "age": 29
      }, {
        "first_name": "Jack",
        "last_name": "Montgomery",
        "age": 28
      }, {
        "first_name": "Gloria",
        "last_name": "Andrews",
        "age": 7
      }, {
        "first_name": "Carolyn",
        "last_name": "Gilbert",
        "age": 50
      }, {
        "first_name": "Stephanie",
        "last_name": "Alvarez",
        "age": 96
      }, {
        "first_name": "Janet",
        "last_name": "Lawrence",
        "age": 73
      }, {
        "first_name": "Steve",
        "last_name": "Perry",
        "age": 1
      }, {
        "first_name": "Denise",
        "last_name": "Gordon",
        "age": 75
      }, {
        "first_name": "Gary",
        "last_name": "Sanders",
        "age": 39
      }, {
        "first_name": "Carlos",
        "last_name": "Hunter",
        "age": 48
      }, {
        "first_name": "Carlos",
        "last_name": "Alvarez",
        "age": 8
      }, {
        "first_name": "Peter",
        "last_name": "Ellis",
        "age": 94
      }, {
        "first_name": "Amanda",
        "last_name": "Gardner",
        "age": 58
      }, {
        "first_name": "Jesse",
        "last_name": "Snyder",
        "age": 98
      }, {
        "first_name": "Bruce",
        "last_name": "Jenkins",
        "age": 70
      }, {
        "first_name": "Elizabeth",
        "last_name": "Stevens",
        "age": 87
      }, {
        "first_name": "Linda",
        "last_name": "Carpenter",
        "age": 19
      }, {
        "first_name": "Kathy",
        "last_name": "Simmons",
        "age": 21
      }, {
        "first_name": "John",
        "last_name": "Stone",
        "age": 53
      }, {
        "first_name": "Jane",
        "last_name": "Davis",
        "age": 54
      }, {
        "first_name": "Ryan",
        "last_name": "Pierce",
        "age": 12
      }, {
        "first_name": "Lawrence",
        "last_name": "Weaver",
        "age": 92
      }, {
        "first_name": "Walter",
        "last_name": "Matthews",
        "age": 75
      }, {
        "first_name": "Jerry",
        "last_name": "Roberts",
        "age": 91
      }, {
        "first_name": "Harold",
        "last_name": "Chavez",
        "age": 50
      }, {
        "first_name": "Jennifer",
        "last_name": "Hudson",
        "age": 67
      }, {
        "first_name": "Daniel",
        "last_name": "Ferguson",
        "age": 57
      }, {
        "first_name": "Cynthia",
        "last_name": "George",
        "age": 60
      }, {
        "first_name": "Ryan",
        "last_name": "Banks",
        "age": 3
      }, {
        "first_name": "Kathy",
        "last_name": "Ramirez",
        "age": 97
      }, {
        "first_name": "Matthew",
        "last_name": "Ross",
        "age": 54
      }, {
        "first_name": "Robin",
        "last_name": "Mendoza",
        "age": 16
      }, {
        "first_name": "Sarah",
        "last_name": "Gray",
        "age": 10
      }, {
        "first_name": "Andrew",
        "last_name": "Turner",
        "age": 61
      }, {
        "first_name": "Karen",
        "last_name": "Morrison",
        "age": 77
      }, {
        "first_name": "Gloria",
        "last_name": "Thompson",
        "age": 72
      }, {
        "first_name": "Tammy",
        "last_name": "Schmidt",
        "age": 50
      }, {
        "first_name": "Elizabeth",
        "last_name": "Hill",
        "age": 67
      }, {
        "first_name": "Roy",
        "last_name": "Ford",
        "age": 98
      }, {
        "first_name": "Judith",
        "last_name": "Jenkins",
        "age": 94
      }, {
        "first_name": "Carol",
        "last_name": "West",
        "age": 36
      }, {
        "first_name": "Kathy",
        "last_name": "Mendoza",
        "age": 51
      }, {
        "first_name": "Douglas",
        "last_name": "Austin",
        "age": 61
      }]
    }]);
